[build-system]
requires = [
  "setuptools>=45",
  "setuptools_scm[toml]>=3.4,<7.0.0",  # For python3.6 support
  "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "varikn"
dynamic = ["version"]

[tool.setuptools_scm]
write_to = "python-wrapper/varikn/_version.py"
